stages:
  -build
#  -Security

build:
  stage: build
  image: node:18.9.1
  script:
    - npm install
  artifacts:
    paths:
      - node_modules


# Security:
#   stage: Security
#   image: 



