stages:
  - build
  - Security
  # - dockerbuild

build:
  stage: build
  image: node:18.9.1
  script:
    - cd mern/backend
    - npm install
  artifacts:
    paths:
      - mern/backend/node_modules


trivy-fs-scan:
  stage: Security
  script:
    - cd mern/backend
    - trivy fs --format table -o trivyfs.html
  artifacts:
    paths:
      - trivyfs.html

      
# build-Docker:
#   stage: dockerbuild
#   script:
#     - docker login -u $username -p $password 
#     - cd mern/backend
#     - docker buld -t prasannakumarsinganamalla431 -f 
#   dependencies:
#     - build  
 