stages:
  - build
#  - Security

build:
  stage: build
  image: node:18.9.1
  script:
    - cd mern/backend
    - npm install
  artifacts:
    paths:
      - node_modules


# Security:
#   stage: Security
#   image:
