FROM node:18.9.1

# Set working directory inside the container
WORKDIR /app

# Copy the necessary files from the current directory into the container
COPY . /app/

# Expose the port your application will run on
EXPOSE 5173

# Start the application by running server.js
CMD ["npm", "run", "dev"]
