stages:
  - build
  - Security
  - dockerbuild

build:
  stage: build
  image: node:18.9.1
  script:
    - cd mern/backend
    - npm install
  artifacts:
    paths:
      - mern/backend/node_modules
  tags:
    - slave2

trivy-fs-backend-scan:
  stage: Security
  # image: aquasec/trivy:latest
  script:
    - wget https://github.com/aquasecurity/trivy/releases/download/v0.18.3/trivy_0.18.3_Linux-64bit.deb
    - sudo dpkg -i trivy_0.18.3_Linux-64bit.deb
    - cd mern/backend
    - trivy fs --format table -o trivyfs.html .
  artifacts:
    paths:
      - mern/backend/trivyfs.html
  tags:
    - slave1


build-backend-Docker:
  stage: dockerbuild
  script:
#    - sudo apt install docker.io -y && sudo usermod -aG docker ubuntu
    - docker login -u $username -p $password 
    - cd mern/backend
    - docker buld -t prasannakumarsinganamalla431/backendMARN:v1 -f dockerfile-ci .
    - docker push prasannakumarsinganamalla431/backendMARN:v1
  dependencies:
    - build  
  tags:
    - slave1   