FROM gcr.io/distroless/nodejs18-debian12

WORKDIR /app

COPY . .

# Copy the node_modules directory into the container
COPY mern/backend/node_modules /app/node_modules

EXPOSE 5050

CMD ["npm", "start"]